import Foundation

// MARK: - Word Pair
struct WordPair {
    let word: String
    let clues: [Difficulty: String]
    let category: String
}

// MARK: - Word Bank
let wordBank: [WordPair] = [
    // Food
    WordPair(word: "Sushi", clues: [.easy: "raw", .medium: "rice", .hard: "seaweed"], category: "Food"),
    WordPair(word: "Pizza", clues: [.easy: "cheese", .medium: "italian", .hard: "slice"], category: "Food"),
    WordPair(word: "Tacos", clues: [.easy: "tortilla", .medium: "mexican", .hard: "filling"], category: "Food"),
    WordPair(word: "Croissant", clues: [.easy: "buttery", .medium: "pastry", .hard: "flaky"], category: "Food"),
    WordPair(word: "Ramen", clues: [.easy: "noodles", .medium: "broth", .hard: "steam"], category: "Food"),
    WordPair(word: "Burrito", clues: [.easy: "beans", .medium: "wrapped", .hard: "foil"], category: "Food"),
    WordPair(word: "Waffles", clues: [.easy: "breakfast", .medium: "grid", .hard: "syrup"], category: "Food"),
    WordPair(word: "Dumpling", clues: [.easy: "steamed", .medium: "dough", .hard: "pleat"], category: "Food"),
    WordPair(word: "Gelato", clues: [.easy: "creamy", .medium: "frozen", .hard: "scoop"], category: "Food"),
    WordPair(word: "Pretzel", clues: [.easy: "salty", .medium: "twisted", .hard: "knot"], category: "Food"),
    WordPair(word: "Lasagna", clues: [.easy: "layered", .medium: "pasta", .hard: "baked"], category: "Food"),
    WordPair(word: "Brownie", clues: [.easy: "chocolate", .medium: "dessert", .hard: "square"], category: "Food"),
    WordPair(word: "Bagel", clues: [.easy: "doughy", .medium: "breakfast", .hard: "hole"], category: "Food"),
    WordPair(word: "Baguette", clues: [.easy: "crusty", .medium: "french", .hard: "loaf"], category: "Food"),
    WordPair(word: "Baklava", clues: [.easy: "honey", .medium: "layers", .hard: "nuts"], category: "Food"),
    WordPair(word: "Biryani", clues: [.easy: "spiced", .medium: "rice", .hard: "aromatic"], category: "Food"),
    WordPair(word: "Bratwurst", clues: [.easy: "sausage", .medium: "grilled", .hard: "mustard"], category: "Food"),
    WordPair(word: "Ceviche", clues: [.easy: "citrus", .medium: "seafood", .hard: "raw"], category: "Food"),
    WordPair(word: "Cheesecake", clues: [.easy: "creamy", .medium: "dessert", .hard: "crust"], category: "Food"),
    WordPair(word: "Churros", clues: [.easy: "fried", .medium: "cinnamon", .hard: "crispy"], category: "Food"),
    WordPair(word: "Clam Chowder", clues: [.easy: "creamy", .medium: "seafood", .hard: "bowl"], category: "Food"),
    WordPair(word: "Couscous", clues: [.easy: "grain", .medium: "north", .hard: "fluffy"], category: "Food"),
    WordPair(word: "Crepe", clues: [.easy: "thin", .medium: "french", .hard: "folded"], category: "Food"),
    WordPair(word: "Curry", clues: [.easy: "spiced", .medium: "sauce", .hard: "aromatic"], category: "Food"),
    WordPair(word: "Donut", clues: [.easy: "fried", .medium: "sweet", .hard: "glazed"], category: "Food"),
    WordPair(word: "Edamame", clues: [.easy: "soy", .medium: "steamed", .hard: "pods"], category: "Food"),
    WordPair(word: "Falafel", clues: [.easy: "fried", .medium: "chickpea", .hard: "spiced"], category: "Food"),
    WordPair(word: "Fish and Chips", clues: [.easy: "fried", .medium: "british", .hard: "battered"], category: "Food"),
    WordPair(word: "Fondue", clues: [.easy: "melted", .medium: "cheese", .hard: "dipping"], category: "Food"),
    WordPair(word: "French Fries", clues: [.easy: "fried", .medium: "potato", .hard: "crispy"], category: "Food"),
    WordPair(word: "Gnocchi", clues: [.easy: "potato", .medium: "italian", .hard: "dumpling"], category: "Food"),
    WordPair(word: "Goulash", clues: [.easy: "stew", .medium: "paprika", .hard: "hearty"], category: "Food"),
    WordPair(word: "Gumbo", clues: [.easy: "stew", .medium: "creole", .hard: "okra"], category: "Food"),
    WordPair(word: "Gyoza", clues: [.easy: "pan", .medium: "dumpling", .hard: "japanese"], category: "Food"),
    WordPair(word: "Hummus", clues: [.easy: "chickpea", .medium: "spread", .hard: "mediterranean"], category: "Food"),
    WordPair(word: "Ice Cream", clues: [.easy: "frozen", .medium: "sweet", .hard: "scoop"], category: "Food"),
    WordPair(word: "Jambalaya", clues: [.easy: "rice", .medium: "creole", .hard: "spicy"], category: "Food"),
    WordPair(word: "Kebab", clues: [.easy: "grilled", .medium: "skewer", .hard: "spiced"], category: "Food"),
    WordPair(word: "Kimchi", clues: [.easy: "fermented", .medium: "korean", .hard: "spicy"], category: "Food"),
    WordPair(word: "Lobster", clues: [.easy: "shellfish", .medium: "butter", .hard: "claws"], category: "Food"),
    WordPair(word: "Macaron", clues: [.easy: "french", .medium: "almond", .hard: "delicate"], category: "Food"),
    WordPair(word: "Mango", clues: [.easy: "tropical", .medium: "sweet", .hard: "juicy"], category: "Food"),
    WordPair(word: "Miso Soup", clues: [.easy: "broth", .medium: "japanese", .hard: "umami"], category: "Food"),
    WordPair(word: "Moussaka", clues: [.easy: "layered", .medium: "eggplant", .hard: "greek"], category: "Food"),
    WordPair(word: "Nachos", clues: [.easy: "cheese", .medium: "chips", .hard: "toppings"], category: "Food"),
    WordPair(word: "Omelette", clues: [.easy: "eggs", .medium: "folded", .hard: "breakfast"], category: "Food"),
    WordPair(word: "Onion Rings", clues: [.easy: "fried", .medium: "crispy", .hard: "battered"], category: "Food"),
    WordPair(word: "Pad Thai", clues: [.easy: "noodles", .medium: "peanuts", .hard: "stir"], category: "Food"),
    WordPair(word: "Paella", clues: [.easy: "rice", .medium: "saffron", .hard: "spanish"], category: "Food"),
    WordPair(word: "Pancakes", clues: [.easy: "fluffy", .medium: "breakfast", .hard: "stack"], category: "Food"),
    WordPair(word: "Peking Duck", clues: [.easy: "crispy", .medium: "chinese", .hard: "glazed"], category: "Food"),
    WordPair(word: "Pho", clues: [.easy: "broth", .medium: "vietnamese", .hard: "herbs"], category: "Food"),
    WordPair(word: "Pierogi", clues: [.easy: "dumpling", .medium: "eastern", .hard: "filled"], category: "Food"),
    WordPair(word: "Poke Bowl", clues: [.easy: "raw", .medium: "hawaiian", .hard: "bowl"], category: "Food"),
    WordPair(word: "Popcorn", clues: [.easy: "popped", .medium: "snack", .hard: "buttery"], category: "Food"),
    WordPair(word: "Poutine", clues: [.easy: "fries", .medium: "gravy", .hard: "cheese"], category: "Food"),
    WordPair(word: "Quesadilla", clues: [.easy: "cheese", .medium: "tortilla", .hard: "melted"], category: "Food"),
    WordPair(word: "Ratatouille", clues: [.easy: "vegetable", .medium: "french", .hard: "stewed"], category: "Food"),
    WordPair(word: "Risotto", clues: [.easy: "creamy", .medium: "rice", .hard: "stirred"], category: "Food"),
    WordPair(word: "Samosa", clues: [.easy: "fried", .medium: "spiced", .hard: "triangular"], category: "Food"),
    WordPair(word: "Sashimi", clues: [.easy: "raw", .medium: "fish", .hard: "sliced"], category: "Food"),
    WordPair(word: "Shawarma", clues: [.easy: "spit", .medium: "wrapped", .hard: "middle"], category: "Food"),
    WordPair(word: "Spring Rolls", clues: [.easy: "crispy", .medium: "asian", .hard: "fried"], category: "Food"),
    WordPair(word: "Steak", clues: [.easy: "grilled", .medium: "beef", .hard: "seared"], category: "Food"),
    WordPair(word: "Sushi Roll", clues: [.easy: "rice", .medium: "seaweed", .hard: "rolled"], category: "Food"),
    WordPair(word: "Tiramisu", clues: [.easy: "coffee", .medium: "italian", .hard: "layered"], category: "Food"),
    WordPair(word: "Tom Yum", clues: [.easy: "soup", .medium: "thai", .hard: "sour"], category: "Food"),
    WordPair(word: "Tzatziki", clues: [.easy: "yogurt", .medium: "cucumber", .hard: "greek"], category: "Food"),
    WordPair(word: "Udon", clues: [.easy: "thick", .medium: "noodles", .hard: "japanese"], category: "Food"),
    WordPair(word: "Vindaloo", clues: [.easy: "curry", .medium: "goan", .hard: "spicy"], category: "Food"),
    WordPair(word: "Yorkshire Pudding", clues: [.easy: "baked", .medium: "british", .hard: "puffy"], category: "Food"),
    // Places
    WordPair(word: "Eiffel Tower", clues: [.easy: "paris", .medium: "iron", .hard: "lattice"], category: "Places"),
    WordPair(word: "Grand Canyon", clues: [.easy: "arizona", .medium: "gorge", .hard: "erosion"], category: "Places"),
    WordPair(word: "Times Square", clues: [.easy: "neon", .medium: "crowded", .hard: "billboard"], category: "Places"),
    WordPair(word: "Sahara Desert", clues: [.easy: "sand", .medium: "arid", .hard: "dunes"], category: "Places"),
    WordPair(word: "Great Wall", clues: [.easy: "china", .medium: "long", .hard: "brick"], category: "Places"),
    WordPair(word: "Amazon Rainforest", clues: [.easy: "jungle", .medium: "rainforest", .hard: "canopy"], category: "Places"),
    WordPair(word: "Mount Everest", clues: [.easy: "tall", .medium: "summit", .hard: "altitude"], category: "Places"),
    WordPair(word: "Venice", clues: [.easy: "canals", .medium: "gondola", .hard: "lagoon"], category: "Places"),
    WordPair(word: "Colosseum", clues: [.easy: "rome", .medium: "arena", .hard: "arches"], category: "Places"),
    WordPair(word: "Niagara Falls", clues: [.easy: "waterfall", .medium: "mist", .hard: "plunge"], category: "Places"),
    WordPair(word: "Acropolis", clues: [.easy: "athens", .medium: "ancient", .hard: "marble"], category: "Places"),
    WordPair(word: "Alhambra", clues: [.easy: "moorish", .medium: "spain", .hard: "palace"], category: "Places"),
    WordPair(word: "Angkor Wat", clues: [.easy: "temple", .medium: "cambodia", .hard: "ruins"], category: "Places"),
    WordPair(word: "Big Ben", clues: [.easy: "london", .medium: "clock", .hard: "gothic"], category: "Places"),
    WordPair(word: "Blue Lagoon", clues: [.easy: "iceland", .medium: "geothermal", .hard: "milky"], category: "Places"),
    WordPair(word: "Buckingham Palace", clues: [.easy: "london", .medium: "royal", .hard: "guards"], category: "Places"),
    WordPair(word: "Burj Khalifa", clues: [.easy: "dubai", .medium: "tallest", .hard: "spire"], category: "Places"),
    WordPair(word: "Chichen Itza", clues: [.easy: "pyramid", .medium: "maya", .hard: "yucatan"], category: "Places"),
    WordPair(word: "Christ the Redeemer", clues: [.easy: "rio", .medium: "statue", .hard: "outstretched"], category: "Places"),
    WordPair(word: "Dead Sea", clues: [.easy: "salty", .medium: "float", .hard: "lowest"], category: "Places"),
    WordPair(word: "Easter Island", clues: [.easy: "moai", .medium: "remote", .hard: "statues"], category: "Places"),
    WordPair(word: "Edinburgh Castle", clues: [.easy: "scotland", .medium: "cliff", .hard: "fortress"], category: "Places"),
    WordPair(word: "Forbidden City", clues: [.easy: "beijing", .medium: "imperial", .hard: "courtyards"], category: "Places"),
    WordPair(word: "Galapagos Islands", clues: [.easy: "wildlife", .medium: "remote", .hard: "turtles"], category: "Places"),
    WordPair(word: "Golden Gate Bridge", clues: [.easy: "san", .medium: "suspension", .hard: "orange"], category: "Places"),
    WordPair(word: "Great Barrier Reef", clues: [.easy: "coral", .medium: "australia", .hard: "diving"], category: "Places"),
    WordPair(word: "Hagia Sophia", clues: [.easy: "istanbul", .medium: "dome", .hard: "byzantine"], category: "Places"),
    WordPair(word: "Hollywood Sign", clues: [.easy: "los", .medium: "hills", .hard: "letters"], category: "Places"),
    WordPair(word: "Iguazu Falls", clues: [.easy: "waterfalls", .medium: "border", .hard: "mist"], category: "Places"),
    WordPair(word: "Louvre", clues: [.easy: "paris", .medium: "museum", .hard: "glass"], category: "Places"),
    WordPair(word: "Machu Picchu", clues: [.easy: "inca", .medium: "mountain", .hard: "ruins"], category: "Places"),
    WordPair(word: "Marina Bay Sands", clues: [.easy: "singapore", .medium: "rooftop", .hard: "infinity"], category: "Places"),
    WordPair(word: "Mont Saint-Michel", clues: [.easy: "tidal", .medium: "france", .hard: "abbey"], category: "Places"),
    WordPair(word: "Mount Fuji", clues: [.easy: "volcano", .medium: "japan", .hard: "snow"], category: "Places"),
    WordPair(word: "Neuschwanstein Castle", clues: [.easy: "bavaria", .medium: "fairytale", .hard: "turrets"], category: "Places"),
    WordPair(word: "Petra", clues: [.easy: "jordan", .medium: "carved", .hard: "rose"], category: "Places"),
    WordPair(word: "Pyramids of Giza", clues: [.easy: "egypt", .medium: "pharaoh", .hard: "limestone"], category: "Places"),
    WordPair(word: "Red Square", clues: [.easy: "moscow", .medium: "kremlin", .hard: "cobbles"], category: "Places"),
    WordPair(word: "Sagrada Familia", clues: [.easy: "gaudi", .medium: "barcelona", .hard: "spires"], category: "Places"),
    WordPair(word: "Santorini", clues: [.easy: "greece", .medium: "caldera", .hard: "whitewash"], category: "Places"),
    WordPair(word: "Statue of Liberty", clues: [.easy: "harbor", .medium: "copper", .hard: "torch"], category: "Places"),
    WordPair(word: "Stonehenge", clues: [.easy: "stones", .medium: "neolithic", .hard: "alignment"], category: "Places"),
    WordPair(word: "Sydney Opera House", clues: [.easy: "sails", .medium: "harbor", .hard: "concrete"], category: "Places"),
    WordPair(word: "Taj Mahal", clues: [.easy: "marble", .medium: "india", .hard: "mausoleum"], category: "Places"),
    WordPair(word: "Tower Bridge", clues: [.easy: "london", .medium: "bascule", .hard: "thames"], category: "Places"),
    WordPair(word: "Uluru", clues: [.easy: "monolith", .medium: "australia", .hard: "sandstone"], category: "Places"),
    WordPair(word: "Versailles", clues: [.easy: "palace", .medium: "france", .hard: "gardens"], category: "Places"),
    WordPair(word: "Yellowstone", clues: [.easy: "geyser", .medium: "park", .hard: "bison"], category: "Places"),
    WordPair(word: "Zion National Park", clues: [.easy: "canyon", .medium: "utah", .hard: "sandstone"], category: "Places"),
    // Objects
    WordPair(word: "Guitar", clues: [.easy: "strings", .medium: "wood", .hard: "fret"], category: "Objects"),
    WordPair(word: "Telescope", clues: [.easy: "stars", .medium: "lenses", .hard: "tripod"], category: "Objects"),
    WordPair(word: "Skateboard", clues: [.easy: "wheels", .medium: "deck", .hard: "grind"], category: "Objects"),
    WordPair(word: "Chandelier", clues: [.easy: "ceiling", .medium: "crystal", .hard: "pendant"], category: "Objects"),
    WordPair(word: "Typewriter", clues: [.easy: "keys", .medium: "vintage", .hard: "ribbon"], category: "Objects"),
    WordPair(word: "Compass", clues: [.easy: "north", .medium: "magnetic", .hard: "bearing"], category: "Objects"),
    WordPair(word: "Hourglass", clues: [.easy: "sand", .medium: "timer", .hard: "grains"], category: "Objects"),
    WordPair(word: "Trampoline", clues: [.easy: "bounce", .medium: "springs", .hard: "rebound"], category: "Objects"),
    WordPair(word: "Binoculars", clues: [.easy: "lenses", .medium: "zoom", .hard: "optics"], category: "Objects"),
    WordPair(word: "Lava Lamp", clues: [.easy: "lava", .medium: "groovy", .hard: "wax"], category: "Objects"),
    WordPair(word: "Accordion", clues: [.easy: "bellows", .medium: "keys", .hard: "squeeze"], category: "Objects"),
    WordPair(word: "Backpack", clues: [.easy: "straps", .medium: "zipper", .hard: "carry"], category: "Objects"),
    WordPair(word: "Barometer", clues: [.easy: "pressure", .medium: "weather", .hard: "mercury"], category: "Objects"),
    WordPair(word: "Basketball", clues: [.easy: "orange", .medium: "bouncy", .hard: "dimpled"], category: "Objects"),
    WordPair(word: "Blender", clues: [.easy: "smoothie", .medium: "blades", .hard: "pitcher"], category: "Objects"),
    WordPair(word: "Boomerang", clues: [.easy: "curved", .medium: "throw", .hard: "return"], category: "Objects"),
    WordPair(word: "Calculator", clues: [.easy: "buttons", .medium: "math", .hard: "lcd"], category: "Objects"),
    WordPair(word: "Camera", clues: [.easy: "lens", .medium: "shutter", .hard: "flash"], category: "Objects"),
    WordPair(word: "Candle", clues: [.easy: "wick", .medium: "wax", .hard: "flame"], category: "Objects"),
    WordPair(word: "Clipboard", clues: [.easy: "clamp", .medium: "paper", .hard: "flat"], category: "Objects"),
    WordPair(word: "Drone", clues: [.easy: "propellers", .medium: "remote", .hard: "hover"], category: "Objects"),
    WordPair(word: "Flashlight", clues: [.easy: "beam", .medium: "battery", .hard: "tube"], category: "Objects"),
    WordPair(word: "Globe", clues: [.easy: "sphere", .medium: "continents", .hard: "spin"], category: "Objects"),
    WordPair(word: "Hammock", clues: [.easy: "fabric", .medium: "ropes", .hard: "swing"], category: "Objects"),
    WordPair(word: "Headphones", clues: [.easy: "ears", .medium: "audio", .hard: "cushion"], category: "Objects"),
    WordPair(word: "Joystick", clues: [.easy: "gaming", .medium: "stick", .hard: "buttons"], category: "Objects"),
    WordPair(word: "Kaleidoscope", clues: [.easy: "colors", .medium: "tube", .hard: "mirrors"], category: "Objects"),
    WordPair(word: "Lantern", clues: [.easy: "light", .medium: "glass", .hard: "handle"], category: "Objects"),
    WordPair(word: "Magnifying Glass", clues: [.easy: "lens", .medium: "enlarge", .hard: "handle"], category: "Objects"),
    WordPair(word: "Metronome", clues: [.easy: "tick", .medium: "tempo", .hard: "pendulum"], category: "Objects"),
    WordPair(word: "Microscope", clues: [.easy: "slides", .medium: "tiny", .hard: "lenses"], category: "Objects"),
    WordPair(word: "Parachute", clues: [.easy: "canopy", .medium: "sky", .hard: "cords"], category: "Objects"),
    WordPair(word: "Piano", clues: [.easy: "keys", .medium: "pedals", .hard: "soundboard"], category: "Objects"),
    WordPair(word: "Pinwheel", clues: [.easy: "spin", .medium: "wind", .hard: "paper"], category: "Objects"),
    WordPair(word: "Projector", clues: [.easy: "beam", .medium: "screen", .hard: "lamp"], category: "Objects"),
    WordPair(word: "Rubiks Cube", clues: [.easy: "twist", .medium: "colors", .hard: "puzzle"], category: "Objects"),
    WordPair(word: "Scissors", clues: [.easy: "blades", .medium: "cut", .hard: "hinge"], category: "Objects"),
    WordPair(word: "Segway", clues: [.easy: "wheels", .medium: "balance", .hard: "electric"], category: "Objects"),
    WordPair(word: "Snow Globe", clues: [.easy: "shaker", .medium: "glitter", .hard: "dome"], category: "Objects"),
    WordPair(word: "Stethoscope", clues: [.easy: "doctor", .medium: "chest", .hard: "tubing"], category: "Objects"),
    WordPair(word: "Sundial", clues: [.easy: "shadow", .medium: "time", .hard: "gnomon"], category: "Objects"),
    WordPair(word: "Thermometer", clues: [.easy: "temperature", .medium: "mercury", .hard: "scale"], category: "Objects"),
    WordPair(word: "Treadmill", clues: [.easy: "running", .medium: "belt", .hard: "gym"], category: "Objects"),
    WordPair(word: "Ukulele", clues: [.easy: "small", .medium: "strings", .hard: "hawaiian"], category: "Objects"),
    WordPair(word: "Violin", clues: [.easy: "bow", .medium: "strings", .hard: "chin"], category: "Objects"),
    WordPair(word: "Windmill", clues: [.easy: "blades", .medium: "wind", .hard: "grind"], category: "Objects"),
    WordPair(word: "Xylophone", clues: [.easy: "bars", .medium: "mallets", .hard: "wood"], category: "Objects"),
    WordPair(word: "Yo-Yo", clues: [.easy: "string", .medium: "spin", .hard: "toy"], category: "Objects"),
    WordPair(word: "Zipper", clues: [.easy: "teeth", .medium: "slide", .hard: "fastener"], category: "Objects"),
    // Activities
    WordPair(word: "Surfing", clues: [.easy: "waves", .medium: "ocean", .hard: "board"], category: "Activities"),
    WordPair(word: "Karaoke", clues: [.easy: "singing", .medium: "mic", .hard: "lyrics"], category: "Activities"),
    WordPair(word: "Rock Climbing", clues: [.easy: "rock", .medium: "ropes", .hard: "crux"], category: "Activities"),
    WordPair(word: "Yoga", clues: [.easy: "stretch", .medium: "poses", .hard: "breath"], category: "Activities"),
    WordPair(word: "Scuba Diving", clues: [.easy: "underwater", .medium: "tanks", .hard: "buoyancy"], category: "Activities"),
    WordPair(word: "Archery", clues: [.easy: "arrows", .medium: "target", .hard: "draw"], category: "Activities"),
    WordPair(word: "Snowboarding", clues: [.easy: "snow", .medium: "slope", .hard: "carve"], category: "Activities"),
    WordPair(word: "Pottery", clues: [.easy: "clay", .medium: "wheel", .hard: "kiln"], category: "Activities"),
    WordPair(word: "Skydiving", clues: [.easy: "parachute", .medium: "freefall", .hard: "canopy"], category: "Activities"),
    WordPair(word: "Fencing", clues: [.easy: "swords", .medium: "foil", .hard: "parry"], category: "Activities"),
    WordPair(word: "Badminton", clues: [.easy: "shuttlecock", .medium: "net", .hard: "racket"], category: "Activities"),
    WordPair(word: "Baseball", clues: [.easy: "bat", .medium: "diamond", .hard: "pitch"], category: "Activities"),
    WordPair(word: "Billiards", clues: [.easy: "cue", .medium: "balls", .hard: "felt"], category: "Activities"),
    WordPair(word: "Bowling", clues: [.easy: "pins", .medium: "lane", .hard: "strike"], category: "Activities"),
    WordPair(word: "Camping", clues: [.easy: "tent", .medium: "fire", .hard: "outdoors"], category: "Activities"),
    WordPair(word: "Cheerleading", clues: [.easy: "pom", .medium: "stunt", .hard: "routine"], category: "Activities"),
    WordPair(word: "Chess", clues: [.easy: "board", .medium: "strategy", .hard: "checkmate"], category: "Activities"),
    WordPair(word: "Cycling", clues: [.easy: "bike", .medium: "pedals", .hard: "helmet"], category: "Activities"),
    WordPair(word: "Dancing", clues: [.easy: "rhythm", .medium: "steps", .hard: "music"], category: "Activities"),
    WordPair(word: "Fishing", clues: [.easy: "rod", .medium: "bait", .hard: "reel"], category: "Activities"),
    WordPair(word: "Golf", clues: [.easy: "swing", .medium: "fairway", .hard: "putt"], category: "Activities"),
    WordPair(word: "Hiking", clues: [.easy: "trail", .medium: "boots", .hard: "summit"], category: "Activities"),
    WordPair(word: "Horseback Riding", clues: [.easy: "saddle", .medium: "reins", .hard: "gallop"], category: "Activities"),
    WordPair(word: "Ice Skating", clues: [.easy: "blades", .medium: "rink", .hard: "glide"], category: "Activities"),
    WordPair(word: "Juggling", clues: [.easy: "balls", .medium: "catch", .hard: "rhythm"], category: "Activities"),
    WordPair(word: "Karate", clues: [.easy: "belt", .medium: "dojo", .hard: "kick"], category: "Activities"),
    WordPair(word: "Knitting", clues: [.easy: "yarn", .medium: "needles", .hard: "stitch"], category: "Activities"),
    WordPair(word: "Meditation", clues: [.easy: "still", .medium: "breath", .hard: "mindful"], category: "Activities"),
    WordPair(word: "Paintball", clues: [.easy: "mask", .medium: "splat", .hard: "cover"], category: "Activities"),
    WordPair(word: "Paragliding", clues: [.easy: "canopy", .medium: "ridge", .hard: "thermal"], category: "Activities"),
    WordPair(word: "Ping Pong", clues: [.easy: "paddle", .medium: "table", .hard: "spin"], category: "Activities"),
    WordPair(word: "Rollerblading", clues: [.easy: "wheels", .medium: "pavement", .hard: "stride"], category: "Activities"),
    WordPair(word: "Rowing", clues: [.easy: "oars", .medium: "boat", .hard: "stroke"], category: "Activities"),
    WordPair(word: "Sailing", clues: [.easy: "mast", .medium: "wind", .hard: "helm"], category: "Activities"),
    WordPair(word: "Skateboarding", clues: [.easy: "ollie", .medium: "ramp", .hard: "deck"], category: "Activities"),
    WordPair(word: "Skiing", clues: [.easy: "slopes", .medium: "poles", .hard: "powder"], category: "Activities"),
    WordPair(word: "Snorkeling", clues: [.easy: "mask", .medium: "reef", .hard: "fins"], category: "Activities"),
    WordPair(word: "Swimming", clues: [.easy: "pool", .medium: "strokes", .hard: "laps"], category: "Activities"),
    WordPair(word: "Table Tennis", clues: [.easy: "paddle", .medium: "net", .hard: "rally"], category: "Activities"),
    WordPair(word: "Tennis", clues: [.easy: "racket", .medium: "court", .hard: "serve"], category: "Activities"),
    WordPair(word: "Volleyball", clues: [.easy: "net", .medium: "spike", .hard: "beach"], category: "Activities"),
    WordPair(word: "Water Polo", clues: [.easy: "pool", .medium: "ball", .hard: "tread"], category: "Activities"),
    WordPair(word: "Weightlifting", clues: [.easy: "barbell", .medium: "gym", .hard: "rep"], category: "Activities"),
    WordPair(word: "Wrestling", clues: [.easy: "mat", .medium: "pin", .hard: "grapple"], category: "Activities"),
    // Animals
    WordPair(word: "Penguin", clues: [.easy: "waddle", .medium: "antarctic", .hard: "tuxedo"], category: "Animals"),
    WordPair(word: "Chameleon", clues: [.easy: "color", .medium: "lizard", .hard: "camouflage"], category: "Animals"),
    WordPair(word: "Octopus", clues: [.easy: "eight", .medium: "tentacles", .hard: "ink"], category: "Animals"),
    WordPair(word: "Flamingo", clues: [.easy: "pink", .medium: "legs", .hard: "filter"], category: "Animals"),
    WordPair(word: "Platypus", clues: [.easy: "duckbill", .medium: "odd", .hard: "mammal"], category: "Animals"),
    WordPair(word: "Jellyfish", clues: [.easy: "sting", .medium: "gelatin", .hard: "pulse"], category: "Animals"),
    WordPair(word: "Peacock", clues: [.easy: "feathers", .medium: "fan", .hard: "iridescent"], category: "Animals"),
    WordPair(word: "Armadillo", clues: [.easy: "armor", .medium: "texas", .hard: "roll"], category: "Animals"),
    WordPair(word: "Narwhal", clues: [.easy: "tusk", .medium: "arctic", .hard: "spiral"], category: "Animals"),
    WordPair(word: "Axolotl", clues: [.easy: "salamander", .medium: "gills", .hard: "regeneration"], category: "Animals"),
    WordPair(word: "Aardvark", clues: [.easy: "ant", .medium: "snout", .hard: "nocturnal"], category: "Animals"),
    WordPair(word: "Albatross", clues: [.easy: "wingspan", .medium: "ocean", .hard: "glide"], category: "Animals"),
    WordPair(word: "Alligator", clues: [.easy: "swamp", .medium: "jaws", .hard: "reptile"], category: "Animals"),
    WordPair(word: "Alpaca", clues: [.easy: "fluffy", .medium: "andes", .hard: "spit"], category: "Animals"),
    WordPair(word: "Antelope", clues: [.easy: "savanna", .medium: "horns", .hard: "swift"], category: "Animals"),
    WordPair(word: "Baboon", clues: [.easy: "primate", .medium: "muzzle", .hard: "troops"], category: "Animals"),
    WordPair(word: "Badger", clues: [.easy: "burrow", .medium: "stripe", .hard: "fierce"], category: "Animals"),
    WordPair(word: "Barracuda", clues: [.easy: "teeth", .medium: "reef", .hard: "fast"], category: "Animals"),
    WordPair(word: "Beaver", clues: [.easy: "dam", .medium: "teeth", .hard: "tail"], category: "Animals"),
    WordPair(word: "Bison", clues: [.easy: "plains", .medium: "herd", .hard: "shaggy"], category: "Animals"),
    WordPair(word: "Blue Whale", clues: [.easy: "largest", .medium: "ocean", .hard: "blowhole"], category: "Animals"),
    WordPair(word: "Capybara", clues: [.easy: "rodent", .medium: "semi", .hard: "chill"], category: "Animals"),
    WordPair(word: "Cheetah", clues: [.easy: "fastest", .medium: "spots", .hard: "sprint"], category: "Animals"),
    WordPair(word: "Cobra", clues: [.easy: "hood", .medium: "venom", .hard: "strike"], category: "Animals"),
    WordPair(word: "Coyote", clues: [.easy: "howl", .medium: "desert", .hard: "clever"], category: "Animals"),
    WordPair(word: "Crab", clues: [.easy: "claws", .medium: "sideways", .hard: "shell"], category: "Animals"),
    WordPair(word: "Dolphin", clues: [.easy: "smart", .medium: "pod", .hard: "click"], category: "Animals"),
    WordPair(word: "Eagle", clues: [.easy: "talon", .medium: "soar", .hard: "prey"], category: "Animals"),
    WordPair(word: "Elephant", clues: [.easy: "trunk", .medium: "tusks", .hard: "herd"], category: "Animals"),
    WordPair(word: "Emu", clues: [.easy: "flightless", .medium: "australia", .hard: "stride"], category: "Animals"),
    WordPair(word: "Fennec Fox", clues: [.easy: "ears", .medium: "desert", .hard: "tiny"], category: "Animals"),
    WordPair(word: "Giraffe", clues: [.easy: "neck", .medium: "spots", .hard: "tall"], category: "Animals"),
    WordPair(word: "Gorilla", clues: [.easy: "silverback", .medium: "knuckle", .hard: "strong"], category: "Animals"),
    WordPair(word: "Hedgehog", clues: [.easy: "spines", .medium: "curl", .hard: "nocturnal"], category: "Animals"),
    WordPair(word: "Hippopotamus", clues: [.easy: "river", .medium: "massive", .hard: "yawn"], category: "Animals"),
    WordPair(word: "Hummingbird", clues: [.easy: "tiny", .medium: "hover", .hard: "iridescent"], category: "Animals"),
    WordPair(word: "Hyena", clues: [.easy: "laugh", .medium: "scavenger", .hard: "clan"], category: "Animals"),
    WordPair(word: "Iguana", clues: [.easy: "lizard", .medium: "spines", .hard: "bask"], category: "Animals"),
    WordPair(word: "Jaguar", clues: [.easy: "rosettes", .medium: "jungle", .hard: "stalk"], category: "Animals"),
    WordPair(word: "Kangaroo", clues: [.easy: "pouch", .medium: "hop", .hard: "outback"], category: "Animals"),
    WordPair(word: "Koala", clues: [.easy: "eucalyptus", .medium: "sleepy", .hard: "marsupial"], category: "Animals"),
    WordPair(word: "Komodo Dragon", clues: [.easy: "lizard", .medium: "island", .hard: "venom"], category: "Animals"),
    WordPair(word: "Lemur", clues: [.easy: "ring", .medium: "madagascar", .hard: "leap"], category: "Animals"),
    WordPair(word: "Leopard", clues: [.easy: "spots", .medium: "tree", .hard: "stealth"], category: "Animals"),
    WordPair(word: "Llama", clues: [.easy: "andes", .medium: "spit", .hard: "wool"], category: "Animals"),
    WordPair(word: "Manatee", clues: [.easy: "gentle", .medium: "seagrass", .hard: "slow"], category: "Animals"),
    WordPair(word: "Meerkat", clues: [.easy: "sentinel", .medium: "desert", .hard: "stand"], category: "Animals"),
    WordPair(word: "Moose", clues: [.easy: "antlers", .medium: "boreal", .hard: "wade"], category: "Animals"),
    WordPair(word: "Orca", clues: [.easy: "blackfish", .medium: "pod", .hard: "dorsal"], category: "Animals"),
    WordPair(word: "Ostrich", clues: [.easy: "fast", .medium: "egg", .hard: "flightless"], category: "Animals"),
    WordPair(word: "Otter", clues: [.easy: "playful", .medium: "river", .hard: "whisker"], category: "Animals"),
    WordPair(word: "Owl", clues: [.easy: "nocturnal", .medium: "silent", .hard: "talon"], category: "Animals"),
    WordPair(word: "Panda", clues: [.easy: "bamboo", .medium: "black", .hard: "cuddly"], category: "Animals"),
    WordPair(word: "Panther", clues: [.easy: "black", .medium: "stalk", .hard: "jungle"], category: "Animals"),
    WordPair(word: "Porcupine", clues: [.easy: "quills", .medium: "nocturnal", .hard: "climb"], category: "Animals"),
    WordPair(word: "Raccoon", clues: [.easy: "mask", .medium: "trash", .hard: "dexterous"], category: "Animals"),
    WordPair(word: "Red Panda", clues: [.easy: "cute", .medium: "bamboo", .hard: "fluffy"], category: "Animals"),
    WordPair(word: "Rhinoceros", clues: [.easy: "horn", .medium: "charge", .hard: "thick"], category: "Animals"),
    WordPair(word: "Sea Turtle", clues: [.easy: "shell", .medium: "ocean", .hard: "migrate"], category: "Animals"),
    WordPair(word: "Seahorse", clues: [.easy: "curly", .medium: "male", .hard: "camouflage"], category: "Animals"),
    WordPair(word: "Sloth", clues: [.easy: "slow", .medium: "hanging", .hard: "algae"], category: "Animals"),
    WordPair(word: "Snow Leopard", clues: [.easy: "mountain", .medium: "spots", .hard: "tail"], category: "Animals"),
    WordPair(word: "Tapir", clues: [.easy: "snout", .medium: "jungle", .hard: "odd"], category: "Animals"),
    WordPair(word: "Toucan", clues: [.easy: "beak", .medium: "rainforest", .hard: "colorful"], category: "Animals"),
    WordPair(word: "Walrus", clues: [.easy: "tusks", .medium: "arctic", .hard: "whisker"], category: "Animals"),
    WordPair(word: "Warthog", clues: [.easy: "tusks", .medium: "savanna", .hard: "wallow"], category: "Animals"),
    WordPair(word: "Wolverine", clues: [.easy: "fierce", .medium: "snow", .hard: "scavenger"], category: "Animals"),
    WordPair(word: "Zebra", clues: [.easy: "stripes", .medium: "herd", .hard: "savanna"], category: "Animals"),
    // Nature
    WordPair(word: "Aurora", clues: [.easy: "lights", .medium: "polar", .hard: "ionized"], category: "Nature"),
    WordPair(word: "Earthquake", clues: [.easy: "seismic", .medium: "fault", .hard: "tremor"], category: "Nature"),
    WordPair(word: "Hurricane", clues: [.easy: "cyclone", .medium: "wind", .hard: "eye"], category: "Nature"),
    WordPair(word: "Lightning", clues: [.easy: "bolt", .medium: "storm", .hard: "flash"], category: "Nature"),
    WordPair(word: "Rainbow", clues: [.easy: "prism", .medium: "arc", .hard: "spectrum"], category: "Nature"),
    WordPair(word: "Tsunami", clues: [.easy: "wave", .medium: "ocean", .hard: "shore"], category: "Nature"),
    WordPair(word: "Volcano", clues: [.easy: "lava", .medium: "erupt", .hard: "magma"], category: "Nature"),
    WordPair(word: "Waterfall", clues: [.easy: "cascade", .medium: "cliff", .hard: "mist"], category: "Nature"),
    // Science
    WordPair(word: "Black Hole", clues: [.easy: "gravity", .medium: "infinite", .hard: "event"], category: "Science"),
    WordPair(word: "DNA", clues: [.easy: "helix", .medium: "genes", .hard: "strand"], category: "Science"),
    WordPair(word: "Gravity", clues: [.easy: "pull", .medium: "mass", .hard: "orbit"], category: "Science"),
    WordPair(word: "Microscope Slide", clues: [.easy: "glass", .medium: "specimen", .hard: "thin"], category: "Science"),
    WordPair(word: "Periodic Table", clues: [.easy: "elements", .medium: "chemistry", .hard: "atomic"], category: "Science"),
    WordPair(word: "Photosynthesis", clues: [.easy: "chlorophyll", .medium: "sun", .hard: "glucose"], category: "Science"),
    WordPair(word: "Solar System", clues: [.easy: "planets", .medium: "orbit", .hard: "sun"], category: "Science"),
    WordPair(word: "Telescope Array", clues: [.easy: "radio", .medium: "dish", .hard: "signals"], category: "Science"),
    WordPair(word: "Vaccine", clues: [.easy: "immunity", .medium: "needle", .hard: "antigen"], category: "Science"),
    // Culture
    WordPair(word: "Superhero", clues: [.easy: "cape", .medium: "powers", .hard: "mask"], category: "Culture"),
    WordPair(word: "Time Travel", clues: [.easy: "paradox", .medium: "future", .hard: "machine"], category: "Culture"),
    WordPair(word: "Zombie", clues: [.easy: "undead", .medium: "horde", .hard: "brains"], category: "Culture"),
    WordPair(word: "Pirate", clues: [.easy: "ship", .medium: "treasure", .hard: "parrot"], category: "Culture"),
    WordPair(word: "Wizard", clues: [.easy: "spell", .medium: "wand", .hard: "robe"], category: "Culture"),
    WordPair(word: "Detective", clues: [.easy: "clue", .medium: "magnifying", .hard: "case"], category: "Culture"),
    WordPair(word: "Circus", clues: [.easy: "tent", .medium: "acrobat", .hard: "clown"], category: "Culture"),
    WordPair(word: "Broadway", clues: [.easy: "theater", .medium: "musical", .hard: "stage"], category: "Culture"),
    WordPair(word: "Video Game", clues: [.easy: "controller", .medium: "pixels", .hard: "level"], category: "Culture"),
    WordPair(word: "Podcast", clues: [.easy: "audio", .medium: "episode", .hard: "mic"], category: "Culture"),
    // Sports
    WordPair(word: "Marathon", clues: [.easy: "26", .medium: "running", .hard: "finish"], category: "Sports"),
    WordPair(word: "Triathlon", clues: [.easy: "swim", .medium: "bike", .hard: "run"], category: "Sports"),
    WordPair(word: "Cricket", clues: [.easy: "bat", .medium: "wicket", .hard: "pitch"], category: "Sports"),
    WordPair(word: "Rugby", clues: [.easy: "scrum", .medium: "oval", .hard: "tackle"], category: "Sports"),
    WordPair(word: "Soccer", clues: [.easy: "goal", .medium: "pitch", .hard: "cleats"], category: "Sports"),
    WordPair(word: "Hockey", clues: [.easy: "puck", .medium: "ice", .hard: "stick"], category: "Sports"),
    WordPair(word: "Lacrosse", clues: [.easy: "net", .medium: "stick", .hard: "field"], category: "Sports"),
    WordPair(word: "Boxing", clues: [.easy: "ring", .medium: "gloves", .hard: "knockout"], category: "Sports"),
    WordPair(word: "Gymnastics", clues: [.easy: "beam", .medium: "flip", .hard: "vault"], category: "Sports"),
    WordPair(word: "Sumo Wrestling", clues: [.easy: "dohyo", .medium: "heavy", .hard: "shiko"], category: "Sports"),
    WordPair(word: "Discus Throw", clues: [.easy: "spin", .medium: "ring", .hard: "release"], category: "Sports"),
    // Plants
    WordPair(word: "Bamboo", clues: [.easy: "hollow", .medium: "fast", .hard: "pandas"], category: "Plants"),
    WordPair(word: "Cactus", clues: [.easy: "spines", .medium: "desert", .hard: "succulent"], category: "Plants"),
    WordPair(word: "Cherry Blossom", clues: [.easy: "pink", .medium: "spring", .hard: "petals"], category: "Plants"),
    WordPair(word: "Dandelion", clues: [.easy: "puff", .medium: "weed", .hard: "seeds"], category: "Plants"),
    WordPair(word: "Fern", clues: [.easy: "fronds", .medium: "shade", .hard: "spores"], category: "Plants"),
    WordPair(word: "Mangrove", clues: [.easy: "roots", .medium: "coast", .hard: "brackish"], category: "Plants"),
    WordPair(word: "Oak Tree", clues: [.easy: "acorn", .medium: "sturdy", .hard: "shade"], category: "Plants"),
    WordPair(word: "Orchid", clues: [.easy: "exotic", .medium: "epiphyte", .hard: "delicate"], category: "Plants"),
    WordPair(word: "Palm Tree", clues: [.easy: "fronds", .medium: "tropical", .hard: "coconut"], category: "Plants"),
    WordPair(word: "Rose", clues: [.easy: "thorns", .medium: "perfume", .hard: "stem"], category: "Plants"),
    WordPair(word: "Sunflower", clues: [.easy: "tall", .medium: "seeds", .hard: "yellow"], category: "Plants"),
    WordPair(word: "Venus Flytrap", clues: [.easy: "snap", .medium: "carnivorous", .hard: "bog"], category: "Plants"),
    WordPair(word: "Willow", clues: [.easy: "weeping", .medium: "flexible", .hard: "riverbank"], category: "Plants"),
    // Technology
    WordPair(word: "Smartphone", clues: [.easy: "touchscreen", .medium: "apps", .hard: "pocket"], category: "Technology"),
    WordPair(word: "Laptop", clues: [.easy: "keyboard", .medium: "portable", .hard: "hinge"], category: "Technology"),
    WordPair(word: "Router", clues: [.easy: "wifi", .medium: "blinking", .hard: "bandwidth"], category: "Technology"),
    WordPair(word: "Satellite", clues: [.easy: "orbit", .medium: "signal", .hard: "dish"], category: "Technology"),
    WordPair(word: "Blockchain", clues: [.easy: "ledger", .medium: "crypto", .hard: "immutable"], category: "Technology"),
    WordPair(word: "Firewall", clues: [.easy: "security", .medium: "packets", .hard: "rules"], category: "Technology"),
    WordPair(word: "USB Drive", clues: [.easy: "flash", .medium: "portable", .hard: "stick"], category: "Technology"),
    WordPair(word: "Bluetooth", clues: [.easy: "wireless", .medium: "pairing", .hard: "short"], category: "Technology"),
    WordPair(word: "QR Code", clues: [.easy: "square", .medium: "scan", .hard: "matrix"], category: "Technology"),
    WordPair(word: "3D Printer", clues: [.easy: "layer", .medium: "filament", .hard: "additive"], category: "Technology"),
    // Fashion
    WordPair(word: "Tuxedo", clues: [.easy: "formal", .medium: "bowtie", .hard: "lapel"], category: "Fashion"),
    WordPair(word: "Sneakers", clues: [.easy: "laces", .medium: "sole", .hard: "casual"], category: "Fashion"),
    WordPair(word: "Sombrero", clues: [.easy: "wide", .medium: "mexican", .hard: "shade"], category: "Fashion"),
    WordPair(word: "Kimono", clues: [.easy: "sash", .medium: "japanese", .hard: "wrap"], category: "Fashion"),
    WordPair(word: "Crown", clues: [.easy: "jewels", .medium: "royal", .hard: "head"], category: "Fashion"),
    WordPair(word: "Leather Jacket", clues: [.easy: "zipper", .medium: "rebel", .hard: "collar"], category: "Fashion"),
    WordPair(word: "Flip Flops", clues: [.easy: "rubber", .medium: "beach", .hard: "thong"], category: "Fashion"),
    WordPair(word: "Beret", clues: [.easy: "french", .medium: "tilted", .hard: "wool"], category: "Fashion"),
    WordPair(word: "Mittens", clues: [.easy: "winter", .medium: "thumb", .hard: "pair"], category: "Fashion"),
    WordPair(word: "Corset", clues: [.easy: "laced", .medium: "tight", .hard: "waist"], category: "Fashion"),
    // Home
    WordPair(word: "Bookshelf", clues: [.easy: "shelves", .medium: "spine", .hard: "wood"], category: "Home"),
    WordPair(word: "Grandfather Clock", clues: [.easy: "pendulum", .medium: "chime", .hard: "tall"], category: "Home"),
    WordPair(word: "Hammock Chair", clues: [.easy: "swing", .medium: "indoor", .hard: "cocoon"], category: "Home"),
    WordPair(word: "Kitchen Island", clues: [.easy: "counter", .medium: "stools", .hard: "prep"], category: "Home"),
    WordPair(word: "Recliner", clues: [.easy: "footrest", .medium: "lever", .hard: "lounge"], category: "Home"),
    WordPair(word: "Vanity", clues: [.easy: "mirror", .medium: "drawers", .hard: "makeup"], category: "Home"),
    WordPair(word: "Wine Rack", clues: [.easy: "bottles", .medium: "cork", .hard: "storage"], category: "Home"),
    WordPair(word: "Beanbag", clues: [.easy: "foam", .medium: "floor", .hard: "slouch"], category: "Home"),
    WordPair(word: "Coat Rack", clues: [.easy: "hooks", .medium: "entryway", .hard: "hats"], category: "Home"),
    WordPair(word: "Nightstand", clues: [.easy: "lamp", .medium: "bedside", .hard: "drawer"], category: "Home"),
    // Music
    WordPair(word: "Saxophone", clues: [.easy: "reed", .medium: "brass", .hard: "jazz"], category: "Music"),
    WordPair(word: "Harmonica", clues: [.easy: "blues", .medium: "blow", .hard: "pocket"], category: "Music"),
    WordPair(word: "Tambourine", clues: [.easy: "jingles", .medium: "shake", .hard: "frame"], category: "Music"),
    WordPair(word: "Maracas", clues: [.easy: "latin", .medium: "rhythm", .hard: "gourd"], category: "Music"),
    WordPair(word: "Cello", clues: [.easy: "bow", .medium: "deep", .hard: "endpin"], category: "Music"),
    WordPair(word: "Trumpet", clues: [.easy: "valves", .medium: "brass", .hard: "mute"], category: "Music"),
    WordPair(word: "Drum Kit", clues: [.easy: "cymbals", .medium: "sticks", .hard: "throne"], category: "Music"),
    WordPair(word: "Turntable", clues: [.easy: "vinyl", .medium: "needle", .hard: "scratch"], category: "Music"),
    WordPair(word: "Kazoo", clues: [.easy: "hum", .medium: "buzz", .hard: "membrane"], category: "Music"),
    WordPair(word: "Bagpipes", clues: [.easy: "scotland", .medium: "drone", .hard: "reed"], category: "Music"),
    // Jobs
    WordPair(word: "Architect", clues: [.easy: "blueprint", .medium: "design", .hard: "scale"], category: "Jobs"),
    WordPair(word: "Barista", clues: [.easy: "espresso", .medium: "latte", .hard: "steam"], category: "Jobs"),
    WordPair(word: "Blacksmith", clues: [.easy: "forge", .medium: "anvil", .hard: "hammer"], category: "Jobs"),
    WordPair(word: "Choreographer", clues: [.easy: "routine", .medium: "dance", .hard: "counts"], category: "Jobs"),
    WordPair(word: "Dentist", clues: [.easy: "drill", .medium: "molars", .hard: "floss"], category: "Jobs"),
    WordPair(word: "Electrician", clues: [.easy: "wires", .medium: "breaker", .hard: "voltage"], category: "Jobs"),
    WordPair(word: "Florist", clues: [.easy: "bouquet", .medium: "vase", .hard: "stems"], category: "Jobs"),
    WordPair(word: "Journalist", clues: [.easy: "deadline", .medium: "byline", .hard: "interview"], category: "Jobs"),
    WordPair(word: "Lighthouse Keeper", clues: [.easy: "beacon", .medium: "fog", .hard: "rotation"], category: "Jobs"),
    WordPair(word: "Paramedic", clues: [.easy: "siren", .medium: "stretcher", .hard: "triage"], category: "Jobs"),
    // Space
    WordPair(word: "Nebula", clues: [.easy: "gas", .medium: "interstellar", .hard: "glow"], category: "Space"),
    WordPair(word: "Comet", clues: [.easy: "tail", .medium: "orbit", .hard: "icy"], category: "Space"),
    WordPair(word: "Asteroid", clues: [.easy: "belt", .medium: "rock", .hard: "crater"], category: "Space"),
    WordPair(word: "Constellation", clues: [.easy: "stars", .medium: "myth", .hard: "pattern"], category: "Space"),
    WordPair(word: "Supernova", clues: [.easy: "explosion", .medium: "bright", .hard: "remnant"], category: "Space"),
    WordPair(word: "Space Station", clues: [.easy: "orbit", .medium: "modules", .hard: "microgravity"], category: "Space"),
    WordPair(word: "Rocket", clues: [.easy: "thrust", .medium: "staging", .hard: "payload"], category: "Space"),
    WordPair(word: "Moon Landing", clues: [.easy: "apollo", .medium: "footprint", .hard: "dust"], category: "Space"),
    // Body
    WordPair(word: "Skeleton", clues: [.easy: "bones", .medium: "joints", .hard: "frame"], category: "Body"),
    WordPair(word: "Heartbeat", clues: [.easy: "pulse", .medium: "lub", .hard: "rhythm"], category: "Body"),
    WordPair(word: "Brainstem", clues: [.easy: "reflex", .medium: "vital", .hard: "bridge"], category: "Body"),
    WordPair(word: "Tonsils", clues: [.easy: "throat", .medium: "immune", .hard: "removed"], category: "Body"),
    WordPair(word: "Eyelash", clues: [.easy: "blink", .medium: "tiny", .hard: "curve"], category: "Body"),
    WordPair(word: "Freckles", clues: [.easy: "sun", .medium: "spots", .hard: "genetic"], category: "Body"),
    WordPair(word: "Taste Buds", clues: [.easy: "tongue", .medium: "sweet", .hard: "papillae"], category: "Body"),
    WordPair(word: "Achilles Heel", clues: [.easy: "tendon", .medium: "weak", .hard: "myth"], category: "Body"),
    // Fantasy
    WordPair(word: "Dragon", clues: [.easy: "wings", .medium: "hoard", .hard: "breath"], category: "Fantasy"),
    WordPair(word: "Phoenix", clues: [.easy: "rebirth", .medium: "ashes", .hard: "flame"], category: "Fantasy"),
    WordPair(word: "Unicorn", clues: [.easy: "horn", .medium: "pure", .hard: "sparkle"], category: "Fantasy"),
    WordPair(word: "Griffin", clues: [.easy: "eagle", .medium: "lion", .hard: "hybrid"], category: "Fantasy"),
    WordPair(word: "Mermaid", clues: [.easy: "tail", .medium: "siren", .hard: "ocean"], category: "Fantasy"),
    WordPair(word: "Minotaur", clues: [.easy: "labyrinth", .medium: "bull", .hard: "horns"], category: "Fantasy"),
    WordPair(word: "Kraken", clues: [.easy: "tentacles", .medium: "ship", .hard: "legend"], category: "Fantasy"),
    WordPair(word: "Yeti", clues: [.easy: "snow", .medium: "footprint", .hard: "himalaya"], category: "Fantasy"),
    // Life
    WordPair(word: "Birthday", clues: [.easy: "candles", .medium: "cake", .hard: "wish"], category: "Life"),
    WordPair(word: "Wedding", clues: [.easy: "vows", .medium: "rings", .hard: "aisle"], category: "Life"),
    WordPair(word: "Graduation", clues: [.easy: "cap", .medium: "diploma", .hard: "tassel"], category: "Life"),
    WordPair(word: "Jet Lag", clues: [.easy: "timezone", .medium: "fatigue", .hard: "circadian"], category: "Life"),
    WordPair(word: "Deja Vu", clues: [.easy: "familiar", .medium: "glitch", .hard: "memory"], category: "Life"),
    WordPair(word: "Luck", clues: [.easy: "chance", .medium: "four", .hard: "rabbit"], category: "Life"),
    WordPair(word: "Procrastination", clues: [.easy: "later", .medium: "deadline", .hard: "delay"], category: "Life"),
    WordPair(word: "Curiosity", clues: [.easy: "question", .medium: "cat", .hard: "explore"], category: "Life"),
]

// MARK: - Word Bank Functions
func getRandomWordPair(difficulty: Difficulty = .medium) -> (word: String, imposterClue: String) {
    let pair = wordBank.randomElement()!
    return (
        word: pair.word,
        imposterClue: normalizeImposterClueToOneWord(pair.clues[difficulty] ?? pair.clues[.medium]!)
    )
}
